name: APIM Release

on:
  release:
    types: [created]

jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: 11.0.16+8
          distribution: 'temurin'

      - name: Build the project
        run: mvn clean package --file pom.xml

      - name: Create Release artifact
        run: |
          mkdir release
          cp target/*.jar release/
          
      - name: Upload Release artifact
        uses: actions/upload-artifact@v3
        with:
          name: release-artifact
          path: release/**

  publish-release:
    needs: create-release
    runs-on: ubuntu-latest
    steps:
      - name: Download Release artifact
        uses: actions/download-artifact@v3
        with:
          name: release-artifact
          path: ./release-artifact

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.event.release.tag_name }}
          release_name: ${{ github.event.release.name }}
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
